{% set version = "0.4.1" %}

package:
  name: ojph
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/ojph/ojph-{{ version }}.tar.gz
  sha256: ef7c1360d574c63f76428898df44d89e22765085a6216089aca55838ad097112

build:
  script: python -m pip install . -vv
  number: 0
  skip: true  # [py<312]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - openjph
  run:
    - python
    - numpy >=1.24

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - ojph

about:
  home: https://github.com/ramonaoptics/ojph
  summary: 'Python bindings for OpenJPH, a JPEG 2000 codec'
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ramonaoptics/ojph

extra:
  recipe-maintainers:
    - hmaarrfk
